services:
  post-service:
    build: .
    container_name: post_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    command: sh -c "npm run migrate && npm run start"

networks:
  vibester-network:
    driver: bridge