apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-conf
  namespace: default
data:
  redis.conf: |
    maxmemory 128mb
    maxmemory-policy allkeys-lru
    appendonly no
    save ""
    protected-mode no
    loglevel warning
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-env
  namespace: default
data:
  REDIS_URL: "redis://redis:6379"
