version: '3.8'
services:
  app:
    build: .
    container_name: user_service
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      - db
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5434/user_db?schema=public
      - JWT_SECRET=${JWT_SECRET}

  db:
    image: postgres:15-alpine
    container_name: user_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: user_db
    ports:
      - "5434:5434"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: