# Middlewares de StripPrefix para remover o prefixo de rota antes de repassar ao serviço.
# Exemplo: /auth/login → /login

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-auth-prefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /auth

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-user-prefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /user

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-establishment-prefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /establishment

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-event-prefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /event

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-scrapping-prefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /scrapping

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-post-prefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /post

---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: strip-payment-prefix
  namespace: default
spec:
  stripPrefix:
    prefixes:
      - /payment

# Middleware para redirecionar HTTP → HTTPS
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-https
  namespace: default
spec:
  redirectScheme:
    scheme: https
    permanent: true
