// Package docs Code generated by swaggo/swag. DO NOT EDIT (regenerate with `swag init -g cmd/api/main.go`).
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Verifica se o serviço está disponível.",
                "produces": ["application/json"],
                "tags": ["Health"],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "Serviço disponível",
                        "schema": { "type": "object", "additionalProperties": { "type": "string" } }
                    }
                }
            }
        },
        "/notifications/2fa": {
            "post": {
                "description": "Gera um código de autenticação de dois fatores, renderiza o template e enfileira o email.",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Notifications"],
                "summary": "Enviar código 2FA",
                "parameters": [
                    {
                        "description": "Dados (to, name)",
                        "name": "notification",
                        "in": "body",
                        "required": true,
                        "schema": { "$ref": "#/definitions/models.Notification" }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Código 2FA enviado",
                        "schema": { "type": "object", "additionalProperties": { "type": "string" } }
                    },
                    "400": {
                        "description": "JSON inválido",
                        "schema": { "type": "object", "additionalProperties": { "type": "string" } }
                    },
                    "500": {
                        "description": "Erro ao renderizar template ou salvar código",
                        "schema": { "type": "object", "additionalProperties": { "type": "string" } }
                    }
                }
            }
        },
        "/notifications/2fa/validate": {
            "post": {
                "description": "Valida um código de dois fatores e o marca como utilizado.",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Notifications"],
                "summary": "Validar código 2FA",
                "parameters": [
                    {
                        "description": "Email e código 2FA",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": { "$ref": "#/definitions/models.ValidateTwoFactorRequest" }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Código válido",
                        "schema": { "type": "object", "additionalProperties": { "type": "boolean" } }
                    },
                    "400": {
                        "description": "JSON inválido",
                        "schema": { "type": "object", "additionalProperties": { "type": "string" } }
                    },
                    "401": {
                        "description": "Código inválido ou expirado",
                        "schema": { "type": "object", "additionalProperties": { "type": "boolean" } }
                    },
                    "500": {
                        "description": "Erro interno",
                        "schema": { "type": "object", "additionalProperties": { "type": "string" } }
                    }
                }
            }
        },
        "/notifications/email": {
            "post": {
                "description": "Enfileira um email genérico para processamento assíncrono.",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Notifications"],
                "summary": "Enviar email genérico",
                "parameters": [
                    {
                        "description": "Dados do email (to, subject, message)",
                        "name": "notification",
                        "in": "body",
                        "required": true,
                        "schema": { "$ref": "#/definitions/models.Notification" }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Email enviado para processamento",
                        "schema": { "type": "object", "additionalProperties": { "type": "string" } }
                    },
                    "400": {
                        "description": "JSON inválido",
                        "schema": { "type": "object", "additionalProperties": { "type": "string" } }
                    }
                }
            }
        },
        "/notifications/reset-password": {
            "post": {
                "description": "Renderiza o template de recuperação de senha e enfileira o email.",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Notifications"],
                "summary": "Enviar email de recuperação de senha",
                "parameters": [
                    {
                        "description": "Dados (to, name, reset_link)",
                        "name": "notification",
                        "in": "body",
                        "required": true,
                        "schema": { "$ref": "#/definitions/models.Notification" }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Email de recuperação enviado para fila",
                        "schema": { "type": "object", "additionalProperties": { "type": "string" } }
                    },
                    "400": {
                        "description": "JSON inválido",
                        "schema": { "type": "object", "additionalProperties": { "type": "string" } }
                    },
                    "500": {
                        "description": "Erro ao renderizar template",
                        "schema": { "type": "object", "additionalProperties": { "type": "string" } }
                    }
                }
            }
        },
        "/notifications/welcome": {
            "post": {
                "description": "Renderiza o template de boas-vindas e enfileira o email.",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["Notifications"],
                "summary": "Enviar email de boas-vindas",
                "parameters": [
                    {
                        "description": "Dados (to, name)",
                        "name": "notification",
                        "in": "body",
                        "required": true,
                        "schema": { "$ref": "#/definitions/models.Notification" }
                    }
                ],
                "responses": {
                    "202": {
                        "description": "Email de boas-vindas enviado",
                        "schema": { "type": "object", "additionalProperties": { "type": "string" } }
                    },
                    "400": {
                        "description": "JSON inválido",
                        "schema": { "type": "object", "additionalProperties": { "type": "string" } }
                    },
                    "500": {
                        "description": "Erro ao renderizar template",
                        "schema": { "type": "object", "additionalProperties": { "type": "string" } }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Notification": {
            "type": "object",
            "properties": {
                "message":    { "type": "string", "example": "Conteúdo do email" },
                "name":       { "type": "string", "example": "João Silva" },
                "reset_link": { "type": "string", "example": "https://vibester.com.br/reset/abc123" },
                "subject":    { "type": "string", "example": "Assunto do email" },
                "to":         { "type": "string", "example": "joao@email.com" }
            }
        },
        "models.ValidateTwoFactorRequest": {
            "type": "object",
            "required": ["email", "code"],
            "properties": {
                "code":  { "type": "string", "example": "482931" },
                "email": { "type": "string", "example": "joao@email.com" }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Notification Service API",
	Description:      "Documentação da API do serviço de notificações do Vibester (emails: genérico, recuperação de senha, boas-vindas e 2FA).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
