apiVersion: v1
kind: Service
metadata:
  name: post-service
  namespace: default
spec:
  selector:
    app: post-service
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: cassandra
  namespace: default
spec:
  selector:
    app: cassandra
  ports:
    - port: 9042
      targetPort: 9042
  clusterIP: None
